api = "0.7"

[extension]
homepage = "https://github.com/paketo-buildpacks/ubi-nodejs-extension"
id = "paketo-buildpacks/ubi-nodejs-extension"
name = "Ubi Node.js Extension"
description = "This extension installs the appropriate Node.js runtime via dnf"

[metadata]
  pre-package = "./scripts/build.sh"
  include-files = ["bin/generate", "bin/detect", "bin/run", "extension.toml"]
